### ISSUE TITLE
Add content for remaining sections

### ISSUE THREAD

**Issue by gosseti** [superhi/nomadsun#20]
If you didn’t get around to it already, add in the remaining content for:

- Iceland
- Bali
- West Coast USA
- Mauritius

**Comment by aildor** [comment]
Two things I can't figure out to do in the Bali section: 

- When I make a gallery of a two-third image and two one-third images (supposed to stack on top of each other) - how do I get the heights to fit, so that the images fits nicely? 

- Also, how do I create a combination of text + image in two columns next to each other? I have tried to create a group in advanced custom field, however I can't get it to work? 

Any helt appreciated, thanks!

**Comment by riklomas** [comment]
Hey @aildor, 

For the first point, we have a video on CSS Grid which might explain more: <https://www.superhi.com/video/introducing-css-grids> but basically the options are:

* to export images at the right ratios
* to switch them from being a `<img>` tag to a generic tag (e.g. `<div>`) with background-image style on it, then to use background-size cover in the CSS so it stretches to fit the sizes

For the second point, do you mean the bit in Day 5 on the screenshot?

Rik
